# Generated by Django 5.2.6 on 2026-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono',
            name='id_sistema',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
