# Generated by Django 5.2.6 on 2026-09-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('id_sistema', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.bono')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.asignacion')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.recibo')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requerimiento', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('id_planilla_parcial', models.IntegerField()),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.recibo')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
            },
        ),
    ]
