# Generated by Django 5.2.6 on 2026-07-07 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
