# Generated by Django 5.2.6 on 2026-09-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidacion.recibo')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
    ]
