# Generated by Django 5.2.6 on 2026-07-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0002_asignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='fecha_asignacion',
            new_name='fecha',
        ),
    ]
