# Generated by Django 5.2.6 on 2026-09-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('liquidacion', '0002_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='escuela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela'),
            preserve_default=False,
        ),
    ]
