# Generated by Django 5.2.6 on 2026-09-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion', '0003_asignacion_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='id_planilla_parcial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
