# Generated by Django 5.2.6 on 2026-09-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fijo', 'Fijo'), ('celular', 'Celular')], max_length=10)),
                ('etiqueta', models.CharField(choices=[('personal', 'Personal'), ('institucional', 'Institucional')], default='personal', max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='escuela.encargado')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
                'unique_together': {('encargado', 'tipo')},
            },
        ),
    ]
