# Generated by Django 5.2.6 on 2026-09-08 08:10

from django.db import migrations


def migrar_telefonos(apps, schema_editor):
    Encargado = apps.get_model('escuela', 'Encargado')
    Telefono = apps.get_model('escuela', 'Telefono')

    for encargado in Encargado.objects.exclude(telefono=''):
        Telefono.objects.create(
            encargado=encargado,
            tipo='celular',
            etiqueta='personal',
            numero=encargado.telefono,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_telefono'),
    ]

    operations = [
        migrations.RunPython(migrar_telefonos, migrations.RunPython.noop),
    ]
