# Generated by Django 5.2.6 on 2026-09-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_migrar_telefonos_existentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='telefono',
        ),
    ]
