# Generated by Django 5.2.6 on 2026-09-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_remove_encargado_telefono'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefono',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='tipo',
        ),
    ]
